added further debugging prints

diff --git a/.github/workflows/lint_template.yaml b/.github/workflows/lint_template.yaml
--- a/.github/workflows/lint_template.yaml
+++ b/.github/workflows/lint_template.yaml
@@ -173,20 +173,20 @@ jobs:
             exit 1
           fi
 
-          curl -s \
+          http_code=$(curl -s \
             -o /tmp/msg_body.txt \
             -w "%{http_code}" \
             -X POST "$URL" \
             -H "Content-Type: application/json" \
-            -d "$payload" > /tmp/msg_code.txt
+            -d "$payload")
 
-          http_code=$(cat /tmp/msg_code.txt)
           body=$(cat /tmp/msg_body.txt)
 
           echo "Res code: $http_code"
+          echo "Res body: $body"
 
-          if [ "$http_code" -lt 200 ] || [ "$http_code" -gt 299 ]; then
-            echo "Webhook failed with HTTP $http_code"
-            [ -n "$body" ] && echo "Response body: $body"
-            exit 1
-          fi
+          # if [ "$http_code" -lt 200 ] || [ "$http_code" -gt 299 ]; then
+          #   echo "Webhook failed with HTTP $http_code"
+          #   [ -n "$body" ] && echo "Response body: $body"
+          #   exit 1
+          # fi
